# Generated by Django 3.1.4 on 2020-12-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MealChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(verbose_name='Submission date')),
                ('invite_sent_date', models.DateTimeField(verbose_name='Invite sent date')),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rsvp.attendee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('guest_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.attendee')),
                ('meal_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsvp.mealchoice')),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.rsvp')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='meal_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsvp.mealchoice'),
        ),
    ]
